class HomePageLocators:
    main_page_logo = '.login_logo'
    username_field = '#user-name'
    password_field = '#password'
    header_of_accepted_logins_list = '.login_credentials h4'
    list_of_accepted_login = '.login_credentials'
    header_of_accepted_password_list = '.login_password h4'
    list_of_accepted_password = '.login_password'
    login_button = '.submit-button'
    empty_error_field = '.error-message-container'
    not_empty_error_field = '.error-message-container.error'
    error_icon = '.error_icon'